### ISSUE TITLE
Can't build with Java 11 and 17 because tools.jar is missing under lib directory of JDK installation

### ISSUE THREAD

**Issue by alperkocatas** [ModelDriven/fUML-Reference-Implementation#42]
I have tried to build fUML reference implementation using JDK 11 and 17, and I received an error in either cases about the dependency `${java.home}/../lib/tools.jar` listed in the pom.xml. The build could not locate `tools.jar` under `lib` directory of my JDK installation. 

After some research, I have reached [this ](https://stackoverflow.com/questions/53707666/how-to-get-tools-jar-for-openjdk-11-on-windows) stackoverflow topic which states that tools.jar was removed from JDK 9 and above. 

Indeed, I could build successfully after installing JDK 8, because the lib directory of JDK 8 version includes the file `tools.jar`. 

On the other hand, Readme of fUML reference implementation states:

> The implementation build requires the following to be installed:
>   Oracle Java Version 8 or above - see http://java.oracle.com/
>   Apache Maven Version 2.2 or above - see http://maven.apache.org/

I kind of feel that the information in current Readme is a bit misleading. I am not sure if this error can be fixed by another method while also using JDK 9 or higher, however, in standard configuration, it looks like building fUML reference implementation needs JDK 8 version exactly.

**Comment by seidewitz** [comment]
Good point. I will change the README to indicate that the build currently doesn't work for version 9 or higher.

**Comment by alperkocatas** [comment]
Thanks.
