### ISSUE TITLE
Support JDK's Beyond 8

### ISSUE THREAD

**Issue by scinnamond** [ModelDriven/fUML-Reference-Implementation#43]
Support JDK's Beyond 8

**Comment by seidewitz** [comment]
The main issue here seems to be the current reliance on `tools.jar`, which went away in JDK 9.

**Comment by seidewitz** [comment]
Resolved in [release 1.5.0a](https://github.com/ModelDriven/fUML-Reference-Implementation/releases/tag/v1.5.0a).
